### ISSUE TITLE
simple-cloudflare-dynamic Unused CSS

### ISSUE THREAD

**Issue by mackenly** [mackenly/quickbiolinks#12]
**Describe the bug**
This template has some left over unused CSS.

In file [worker.js](https://github.com/mackenly/quickbiolinks/blob/master/templates/simple-cloudflare-dynamic/worker.js)
Line 123-126 can be cut out.

Line 137 should be more specific so that hyperlinks added by the user don't have declaration removed. Example fix is:

```css
#credit a, li a {
    text-decoration: none;
    color: inherit;
}
```
